### ISSUE TITLE
Delete Frame

### ISSUE THREAD

**Issue by rajinderpalsingh2001** [dsc-x/omg-frames-api#11]
Delete Frame api wanted.So that User can also Delete the Frame if he/she wants.

**Comment by arnabsen1729** [comment]
Good point. I think when GET request is made to `/frames` instead of getting an array of frames, we will have to return a key and data. 
```
frameObj: {
   key: 
   value:
}
```

and we will return `frameObject[]`. So when the DELETE request will be sent the key of the frame has to be sent along with the request. For e.g.

**DELETE** `/frames?key=<key_of_frame>`  [ API Key in the header]

Will delete that frame.

I will update the APIs and specify them in the APIdocs.

**Comment by arnabsen1729** [comment]
Final changes are mentioned in the PR description. https://github.com/dsc-x/omg-frames-api/pull/12
